clear,clc
importdata('lamost.csv');
date=ans.data;
ra=date(:,1);
dec=date(:,2);
teff=date(:,3);
teff_err=date(:,4);
logg=date(:,5);
logg_err=date(:,6);
feh=date(:,7);
feh_err=date(:,8);
rv=date(:,9);
rv_err=date(:,10);
temp=logg;
ra=ra(temp>4.0);
dec=dec(temp>4.0);
teff=teff(temp>4.0);
logg=logg(temp>4.0);
feh=feh(temp>4.0);
rv_err=rv_err(temp>4.0);
temp=teff;
ra=ra(4000<temp<8000);
dec=dec(4000<temp<8000);
teff=teff(4000<temp<8000);
logg=logg(4000<temp<8000);
feh=feh(04000<temp<8000);
rv_err=rv_err(4000<temp<8000);


figure
subplot(1,3,1)
plot(ra,dec,'mh','markersize',1)
title('figure1')
xlabel('ra')
ylabel('dec')
legend('dec')
subplot(1,3,2)
scatter(teff,logg,1,feh)
title('figure2')
xlabel('teff')
ylabel('logg')
legend('logg')
subplot(1,3,3)
hist(rv_err,100)
title('figure')
xlabel('rv_err')
ylabel('f')
legend('rv_err')

